---
ansible_connection: local
ansible_python_interpreter: "{{ ansible_playbook_python }}"
superuser_group: wheel

timezone: Asia/Bangkok

config_data:
  linux:
    general:
      browser: "brave"
      launcher: "fuzzel"
      locker: "swaylock -f -c 089966"
      terminal: "footclient"
      powermenu: "nwg-bar -t ~/.config/nwg-bar/exit-bar/bar.json -s ~/.config/nwg-bar/exit-bar/style.css"
    fonts:
      latin:
        ui: "Inter Display"
        sans: "Roboto"
        serif: "Noto Serif"
        monospace: "Google Sans Code"
        ui_monospace: "Google Sans Code"
        terminal_monospace: "GeistMono Nerd Font"
      thai:
        sans: "Noto Sans Thai Looped"
        serif: "Noto Serif Thai"
        monospace: "Noto Serif Thai"
