---
- name: Install packages
  become: true
  package:
    name:
      - tailscale
      - nvtop
      - yt-dlp
      - qbittorrent
      - aria2
      - signal-desktop
    state: present
- name: Install package (AUR)
  become: true
  kewlfft.aur.aur:
    name:
      - media-downloader
      # - gallery-dl-bin
    state: present
