- name: Setup local workstation
  hosts: hevonen-orbit
  roles:
    - role: base
    - role: base-graphical
      when: not ansible_facts['is_chroot']
    - role: dev
      when: not ansible_facts['is_chroot']
    - role: work
      when: not ansible_facts['is_chroot']
