---
- name: Set {{ it.module }} boot time of {{ it.pam_name }} PAM (auth)
  become: true
  community.general.pamd:
    name: "{{ it.pam_name }}"
    type: auth
    control: include
    module_path: system-local-login
    new_type: auth
    new_control: optional
    new_module_path: "{{ it.module }}"
    state: after

- name: Set {{ it.module }} boot time of {{ it.pam_name }} PAM (session)
  become: true
  community.general.pamd:
    name: "{{ it.pam_name }}"
    type: session
    control: include
    module_path: system-local-login
    new_type: auth
    new_control: optional
    new_module_path: "{{ it.module }}"
    state: after
