---
- name: Install Fonts
  become: true
  package:
    name:
      - ttf-jetbrains-mono
      - ttf-cascadia-code
      - ttf-liberation
      - ttf-roboto
      - ttf-roboto-mono
      - ttf-ibm-plex
      - inter-font
      # - adobe-source-serif-fonts
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      # - ttf-jetbrains-mono-nerd
      # - ttf-cascadia-code-nerd
      - otf-geist-mono-nerd
    state: present

- name: Apple custom fontconfig
  become: true
  vars:
    fonts: "{{ config_data['linux']['fonts'] }}"
  template:
    src: custom_fontconfig.conf.j2
    dest: /usr/share/fontconfig/conf.avail/99-custom.conf
    mode: "644"
  register: fc
  notify:
    - Rebuild Font Cache

- name: Symlink custom config
  become: true
  file:
    src: "{{ fc.dest }}"
    dest: /etc/fonts/conf.d/99-custom.conf
    state: link
  notify:
    - Rebuild Font Cache
