---
- name: Remove gnome-keyring PAM module
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/pam.d/{{ item }}"
    regexp: "pam_gnome_keyring.so"
    state: absent
  loop:
    - login
    - greetd
