---
- name: Install packages
  become: true
  package:
    name:
      - fnm
      - bun
      - pulumi
      - biome
      - filezilla
      - libreoffice-fresh
    state: present
- name: Install packages (AUR)
  kewlfft.aur.aur:
    name:
      - netbird-bin
      - google-cloud-cli
    state: present
- name: Enable netbird socket
  become: true
  systemd:
    name: netbird@main.service
    state: started
    enabled: true
    masked: false
