---
- name: Install packages
  become: true
  package:
    name:
      - filezilla
      - libreoffice-fresh
    state: present
- name: Install packages (AUR)
  kewlfft.aur.aur:
    name:
      - netbird-bin
    state: present
- name: Enable netbird socket
  become: true
  systemd:
    name: netbird@main.service
    state: started
    enabled: true
    masked: false
